import pygame

# Colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GRAY = (200, 200, 200)

# Folders
IMAGE_FOLDER = '../Assets/Images'

# Constants
MAX_WIDTH = 40
MAX_HEIGHT = 28
GRID_SIZE = 60
GRID_WIDTH = 20
GRID_HEIGHT = 13
WINDOW_WIDTH = MAX_WIDTH * 30
WINDOW_HEIGHT = MAX_HEIGHT * 30
SIDEBAR_WIDTH = 200
WINDOW_SIZE = (WINDOW_WIDTH + SIDEBAR_WIDTH, WINDOW_HEIGHT)
BUTTON_HEIGHT = 40
PLAYER_IMAGE_SIZE = (45, 60)
FRAME_DELAY = 5
STATE_DELAY = 30

# Initialize Pygame
pygame.init()
font = pygame.font.SysFont('Arial', 18)
